### PR TITLE
Better (smaller) amount of transitive dependencies

### PR DESCRIPTION
**Pull request by mstahv**

### CODE REVIEW

**Review by ZheSun88 — DISMISSED** [review]

**Review by samie — APPROVED** [review]

**Comment by samie** [comment]
Noticed in 2cc2769d5db2c7e7d187ad7ee9581d64c973f2b7 @TatuLund included servlet API. Is this needed?

**Comment by TatuLund** [comment]
@samie Yes, servlet API is needed. You will end up having very weird errors if you do not have it.

**Comment by mstahv** [comment]
Weird errors where? When actually using something from servlet api? Isn't that quite rare?

**Comment by mstahv** [comment]
If possible, I'd minimise all servlet dependencies as that makes add-ons incompatible then with Vaadin 24, where package name changes. And for the future if/when we start to support non-servlet deployments.

**Comment by samie** [comment]
The project and dependency optimisations (except the servlet dependency) from both of the PRs (#380 and #385) were merged to default branch, if you want to test that for any errors? 

This might be a bug workaround?  Then we should document it as todo item and report the bug. 

As a rule of thumb: we should abstract the servlet API from Vaadin applications/add-ons. If it is really a servlet specific functionality you are building you should add it separately.

**Comment by TatuLund** [comment]
E.g. in ProtoTools you will get

type argument org.vaadin.addons.tatu.prototools.ItemRemoveEvent is not within bounds of type-variable T

here

https://github.com/TatuLund/ProtoTools/blob/master/src/main/java/org/vaadin/addons/tatu/prototools/ItemRemoveEvent.java

If servlet API is missing

**Comment by mstahv** [comment]
I tried with ProtoTools project and compilation issues there arise indeed if one removes servlet-api. All related to accessing VaadinSession (which depends on javax.servlet.http.HttpSession ). Now the question is, how many add-ons need it. I wouldn't keep it here based on one or two, even if it does not bring it as transitive dependency when declared as provided. For three I could put it there as commented out with an explanation that for some hard core hacks you need to uncomment this 😁

**Pull request merged**
